[package]
name = "rust-heightmap"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
image = "0.25.5"
rayon = "1.10.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
